stages:
  - build
  - docs

extension:
  stage: build
  image: php:5.6
  script:
    - rm -rf /builds/epartment/package
    - apt-get update
    - apt-get install -y wget unzip gzip
    - cd /builds/epartment/cmgroep-idin
    - tar cvf ../CMGroep_Idin.tar . --exclude=.git --exclude=dev_assets --exclude=ext-config.php --exclude=.gitignore --exclude=.gitlab-ci.yml
    - cd ..
    - rm -rf MagentoTarToConnect-master
    - wget https://github.com/astorm/MagentoTarToConnect/archive/master.zip
    - unzip master.zip
    - rm master.zip
    - php MagentoTarToConnect-master/magento-tar-to-connect.php ./cmgroep-idin/ext-config.php
    - mkdir -p ./cmgroep-idin/build
    - mv /builds/epartment/package/*.tgz ./cmgroep-idin/build/
#  only:
#    - tags
  artifacts:
    name: "Extension"
    paths:
      - build/*.tgz

docs:
  stage: docs
  image: python:2.7
  before_script:
    # Install ssh-agent if not already installed, it is required by Docker.
    # (change apt-get to yum if you use a CentOS-based image)
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

    # Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)

    # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    - ssh-add <(echo "$SSH_PRIVATE_KEY")

    # For Docker builds disable host key checking.
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - apt-get update
    - apt-get install -y openssh-client
    - cd build
    - extension_filename=$(ls | grep tgz)
    - extension_url='http:\/\/docs.epartment.nl\/idin\/releases\/'$extension_filename
    - ssh -p 339 epartment@production119.hipex.io 'mkdir -p ~/domains/docs.epartment.nl/public_html/idin/releases'
    - scp -P 339 *.tgz epartment@production119.hipex.io:~/domains/docs.epartment.nl/public_html/idin/releases/
    - cd ..
    - pip install --upgrade pip
    - pip install --upgrade virtualenv
    - cd /builds/epartment/cmgroep-idin/dev_assets/documentation/src
    - sed -i 's/EXTENSION_TITLE_PLACEHOLDER/'$extension_filename'/g' mkdocs.yml
    - sed -i 's/EXTENSION_FILE_PLACEHOLDER/'$extension_url'/g' mkdocs.yml
    - pip install -r requirements.txt
    - mkdocs build
    - mkdir -p /builds/epartment/cmgroep-idin/build
    - cd /builds/epartment/cmgroep-idin/dev_assets/documentation/src/site
    - scp -P 339 -r ./* epartment@production119.hipex.io:~/domains/docs.epartment.nl/public_html/idin/
#  only:
#    - tags