image: php:5.6

stages:
  - build

run-build:
  stage: build
  script:
    - apt-get update
    - apt-get install -y wget
    - cd /builds/epartment/cmgroep-idin
    - tar cvf ../CMGroep_Idin.tar .
    - cd ..
    - wget https://github.com/astorm/MagentoTarToConnect/archive/master.zip
    - unzip master.zip
    - rm master.zip
    - php MagentoTarToConnect-master/magento-tar-to-connect.php ./cmgroep-idin/ext-config.php
  only:
    - master
  artifacts:
    paths:
      - /builds/epartment/*.tar.gz