image: php:5.6

stages:
  - build

extension:
  stage: build
  script:
    - rm -rf /builds/epartment/package
    - apt-get update
    - apt-get install -y wget unzip gzip
    - cd /builds/epartment/cmgroep-idin
    - tar cvf ../CMGroep_Idin.tar . --exclude=.git --exclude=dev_assets --exclude=ext-config.php --exclude=.gitignore --exclude=.gitlab-ci.yml
    - cd ..
    - rm -rf MagentoTarToConnect-master
    - wget https://github.com/astorm/MagentoTarToConnect/archive/master.zip
    - unzip master.zip
    - rm master.zip
    - php MagentoTarToConnect-master/magento-tar-to-connect.php ./cmgroep-idin/ext-config.php
    - mkdir -p ./cmgroep-idin/build
    - mv /builds/epartment/package/*.tgz ./cmgroep-idin/build/
#  only:
#    - tags
  artifacts:
    paths:
      - build/*.tgz

docs:
  stage: build
  script:
#    - rm /builds/epartment/cmgroep-idin/build/documentation.tar.gz
    - pwd
    - apt-get update
    - apt-get install -y python python-pip python-dev build-essential
    - pip install --upgrade pip
    - pip install --upgrade virtualenv
    - cd /builds/epartment/cmgroep-idin/dev_assets/documentation/src
    - pip install -r requirements.txt
    - mkdocs build
    - mkdir -p /builds/epartment/cmgroep-idin/build
    - tar cvf /builds/epartment/cmgroep-idin/build/documentation.tar.gz /builds/epartment/cmgroep-idin/dev_assets/documentation/src/site/*
#  only:
#    - tags
  artifacts:
    paths:
      - build/*.tar.gz