<?php
/**
 * MIT License
 *
 * Copyright (c) 2016 CM Groep
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * @category   CMGroep
 * @package    Idin
 * @author     Epartment Ecommerce B.V. <support@epartment.nl>
 * @copyright  2016-2017 CM Groep
 * @license    http://www.opensource.org/licenses/mit-license.html  MIT License
 */
?>
<div class="account-login idin">
    <div class="page-title">
        <h1><?php echo $this->__('Login or Create an Account with iDIN'); ?></h1>
    </div>
    <form action="<?php echo $this->getFormAction(); ?>" method="post" class="idin-login-panel" id="idin-login-form">
        <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>">
        <div class="info">
            <div class="idin-logo"></div>
            <div class="introduction">
                <p><?php echo $this->__('iDIN is a secure way of identifying yourself with the merchant. It enables quick registration and login through your bank.') ?></p>
            </div>
        </div>
        <div class="select-issuer">
            <div class="form-group">
                <label for="idin_issuer_select"><?php echo $this->__('Select your bank') ?></label>
                <?php echo $this->getIssuerSelectHtml(); ?>
            </div>
        </div>
        <div class="actions">
            <div class="action-wrapper">
                <?php if($this->registrationEnabled()): ?>
                    <button type="submit" class="button register" name="form_action" value="register" title="<?php echo $this->__('Register with iDIN'); ?>"><span><span><?php echo $this->__('Register with iDIN'); ?></span></span></button>
                <?php endif; ?>
                <?php if($this->loginEnabled()): ?>
                    <button type="submit" class="button login" name="form_action" value="login" title="<?php echo $this->__('Login with iDIN'); ?>"><span><span><?php echo $this->__('Login with iDIN'); ?></span></span></button>
                <?php endif; ?>
            </div>
        </div>
    </form>
    <script type="text/javascript">
        var idinForm = new VarienForm('idin-login-form');
    </script>
</div>