<?php
/**
 * MIT License
 *
 * Copyright (c) 2016 CM Groep
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * @category   CMGroep
 * @package    Idin
 * @author     Epartment Ecommerce B.V. <support@epartment.nl>
 * @copyright  2016-2017 CM Groep
 * @license    http://www.opensource.org/licenses/mit-license.html  MIT License
 */
?>
<?php if ($this->shouldShow()): ?>
    <?php if ($this->isIdinLoginEnabled()): ?>
        <div class="customer-account-idin-info <?php if ($this->customerHasIdin()): ?>idin-connected<?php endif; ?>">
            <div class="idin-logo"></div>
            <div class="idin-details">
                <?php if ($this->customerHasIdin()): ?>
                    <span><?php echo $this->__('Your account is connected with iDIN!'); ?></span>
                <?php elseif ($this->isIdinLoginEnabled()): ?>
                    <span>
                        <b><?php echo $this->__('Connect with iDIN'); ?></b><br/>
                        <?php echo $this->__('Connect your account with iDIN and benefit from faster login.'); ?>
                    </span>
                    <div class="action-wrapper">
                        <form action="<?php echo $this->getConnectWithIdinUrl(); ?>" method="post">
                            <?php echo $this->getIssuerSelectHtml(); ?>
                            <button type="submit" class="button"><?php echo $this->__('Connect with iDIN') ?></button>
                        </form>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($this->isIdinAgeVerificationEnabled()): ?>
    <div class="customer-account-idin-info <?php if ($this->customerHasVerifiedAge()): ?>age-verified<?php endif; ?>">
        <div class="idin-logo"></div>
        <div class="idin-details">
            <div class="age-verification">
                <?php if ($this->customerHasVerifiedAge()): ?>
                    <span><?php echo $this->__('Your age has been verified through iDIN.'); ?></span>
                <?php else: ?>
                    <span>
                        <b><?php echo $this->__('Verify your age with iDIN'); ?></b><br/>
                        <?php echo $this->__('Your age has not yet been verified through iDIN or you&apos;re not at least 18 years of age'); ?>
                    </span>
                    <div class="action-wrapper">
                        <form action="<?php echo $this->getVerifyAgeWithIdinUrl(); ?>" method="post">
                            <?php echo $this->getIssuerSelectHtml(); ?>
                            <button type="submit" class="button"><?php echo $this->__('Verify age with iDIN') ?></button>
                        </form>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
    </div>
<?php endif; ?>

<?php /* Re-add original customer account info */ ?>
<?php echo $this->getChildHtml('info'); ?>
