site_name: CM iDIN Magento Extensie
site_description: De officiële iDIN extensie van CM voor Magento
site_author: Epartment E-Commerce
site_url: http://www.cm.nl/

theme: 'material'
theme_dir: '../theme/material'

language: 'nl'

copyright: 'CM Groep iDIN Extensie voor Magento - &copy; CM Groep 2016 - 2017'

extra:
  palette:
    primary: 'idin-blue'
    accent: 'idin-coral'
  font:
      text: 'Overpass'
      code: 'Overpass Mono'

markdown_extensions:
 - admonition
 - toc(permalink=true)
 - pymdownx.betterem(smart_enable=all)
 - pymdownx.emoji:
       emoji_generator: !!python/name:pymdownx.emoji.to_svg
 - pymdownx.magiclink
 - pymdownx.tasklist(custom_checkbox=true)
 - pymdownx.tilde
 - pymdownx.smartsymbols
 - pymdownx.critic

pages:
  - Introductie: index.md
  - Functionaliteiten:
    - Registratie met iDIN: features/registration.md
    - Authenticatie met iDIN: features/authentication.md
    - Leeftijdsverificatie met iDIN: features/age_verification.md
  - Installatie: installation.md
  - Configuratie:
    - Algemeen: configuration/common.md
    - Registratie configureren: configuration/registration.md
    - Authenticatie configureren: configuration/authentication.md
    - Leeftijdsverificatie configureren: configuration/age_verification.md
  - Veel gestelde vragen: faq.md
  - Ondersteuning: support.md
  - Changelog: changelog.md

# URL for extension download
extension:
  title: official-idin-magento-extension-1.0.0.tgz
  file: http://docs.epartment.nl/idin/releases/official-idin-magento-extension-1.0.0.tgz
