<?php
/**
 * MIT License
 *
 * Copyright (c) 2017 CM Groep
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * @category   CMGroep
 * @package    Idin
 * @author     Epartment Ecommerce B.V. <support@epartment.nl>
 * @copyright  2016-2017 CM Groep
 * @license    http://www.opensource.org/licenses/mit-license.html  MIT License
 */
?>

<div class="entry-edit customer-details-idin">
    <div class="entry-edit-head">
        <h4 class="icon-head head-customer-view"><?php echo $this->__('iDIN') ?></h4>
    </div>
    <fieldset>
        <table cellspacing="2" class="box-left">
            <tr>
                <td class="idin-cell">
                    <img class="logo-idin" src="<?php echo $this->getSkinUrl('cm/idin/images/logos/iDIN.svg'); ?>" alt="<?php echo $this->__('iDIN'); ?>">
                </td>
                <td class="idin-details">
                    <?php if ($this->getCustomerIdinConnected()): ?>
                        <strong>- <?php echo $this->__('iDIN login is enabled for this customer.'); ?></strong><br />
                    <?php endif; ?>
                    <?php if ($this->getCustomerAgeVerified()): ?>
                        <strong>- <?php echo $this->__('The customer has verified it&apos;s age through iDIN.'); ?></strong>
                    <?php endif; ?>
                </td>
            </tr>
        </table>
    </fieldset>
</div>
